---
models:
    gpt:
        api_base: https://api.openai.com/v1
        api_key:

    claude:
        api_key:

    bard:
        api_base: https://bard.google.com
        api_key:

    minimax:
        api_base: https://api.minimax.chat
        group_id:
        jwt:

    spark:
        api_base: wss://spark-api.xf-yun.com
        app_id:
        ak:
        sk:

    internlm:
        api_base:
...


