---
models:
    internlm-chat-7b:
        provider: internlm
        webui:
            avatar: 'https://oss.openmmlab.com/frontend/OpenAOE/internlm.svg'
            background: 'linear-gradient(rgb(3 26 108 / 85%) 0%, rgb(29 60 161 / 85%) 100%)'
        api:
            api_base: http://localhost:23333
    gpt-3.5-turbo:
        provider: openai
        webui:
            avatar: 'https://oss.openmmlab.com/frontend/OpenAOE/openai.svg'
            background: 'linear-gradient(180deg, rgba(156, 206, 116, 0.15) 0%, #1a8d15 100%)'
        api:
            api_base: https://api.openai.com/v1
            api_key:
    gpt-4:
        provider: openai
        webui:
            avatar: 'https://oss.openmmlab.com/frontend/OpenAOE/openai.svg'
            background: 'linear-gradient(180deg, rgba(156, 206, 116, 0.15) 0%, #08be00 100%)'
        api:
            api_base: https://api.openai.com/v1
            api_key:
    claude-1:
        provider: claude
        webui:
            avatar: 'https://oss.openmmlab.com/frontend/OpenAOE/claude.svg'
            background: 'linear-gradient(180deg, rgba(141, 90, 181, 0.15) 0%, rgba(106, 39, 123, 0.7) 53.12%, #663E9A 100%)'
        api:
            api_base: https://api.anthropic.com
            api_key:
    claude-1-100k:
        provider: claude
        webui:
            avatar: 'https://oss.openmmlab.com/frontend/OpenAOE/claude.svg'
            background: 'linear-gradient(180deg, rgba(141, 90, 181, 0.15) 0%, rgba(106, 39, 123, 0.7) 53.12%, #663E9A 100%)'
        api:
            api_base: https://api.anthropic.com
            api_key:
    chat-bison-001:
        provider: google
        webui:
            avatar: 'https://oss.openmmlab.com/frontend/OpenAOE/google-palm.webp'
            isStream: false
            background: 'linear-gradient(180deg, rgba(181, 90, 90, 0.15) 0%, #fa5ab1 100%)'
        api:
            api_base: https://generativelanguage.googleapis.com
            api_key:
    gemini-pro:
        provider: google
        webui:
            avatar: 'https://oss.openmmlab.com/frontend/OpenAOE/google-palm.webp'
            isStream: true
            background: 'linear-gradient(#b55a5a26 0%, #fa5ab1 100%)'
        api:
            api_base: https://generativelanguage.googleapis.com
            api_key:
    abab5-chat:
        provider: minimax
        webui:
            avatar: 'https://oss.openmmlab.com/frontend/OpenAOE/minimax.png'
            background: 'linear-gradient(180deg, rgba(207, 72, 72, 0.15) 0%, rgba(151, 43, 43, 0.7) 53.12%, #742828 100%)'
        api:
            api_base: https://api.minimax.chat
            group_id:
            jwt:
    spark:
        provider: spark
        webui:
            avatar: 'https://oss.openmmlab.com/frontend/OpenAOE/spark.svg'
            isStream: false
            background: 'linear-gradient(180deg, rgba(72, 72, 207, 0.15) 0%, #7498be 100%)'
        api:
            api_base: wss://spark-api.xf-yun.com/v2.1/chat
            app_id:
            ak:
            sk:
    mistral-7b:
        provider: mistral
        webui:
            avatar: 'https://oss.openmmlab.com/frontend/OpenAOE/mistral.webp'
            isStream: true
            background: 'linear-gradient(#4848cf26 0%, #7498be 100%)'
            path: '/v1/mistral/v1/mistral/chat'
            payload:
                messages: [ ]
                model: mistral
                prompt: ""
                role_meta:
                    user_name: "user"
                    bot_name: "assistant"
                stream: true
        api:
            api_base: http://localhost:11434
            app_id:
            ak:
            sk:
...
