TYPE_BOT = "bot"
TYPE_USER = "user"
TYPE_SYSTEM = "system"

DATE_PATTERN = "%Y%m%d"
TIMEOUT_SECONDS = 30

VENDOR_OPENAI = "openai"
VENDOR_MINIMAX = "minimax"
VENDOR_GOOGLE = "google"
VENDOR_XUNFEI = "spark"
VENDOR_CLAUDE = "claude"
VENDOR_INTERNLM = "internlm"

DEFAULT_TIMEOUT_SECONDS = 600

